### ISSUE TITLE
Why is "Today" the same as "All Time"?

### ISSUE THREAD

**Issue by zenbug** [24hoursmedia-craftcms/views-work#103]
I would think "Today" meant "Totals for today only," but from what I can tell, "Today" is the same as "All-time." 

See the attached screenshot of the control panel widget. I know for a fact that this article was not viewed that many times today. Any entry that has existed before today and has ever been viewed before should have fewer Today views than All Time views. 

I'm seeing the same issue in my templates when I use `entry.viewsWork.today`.

Am I misunderstanding what "Today" represents?

![Screenshot 2023-07-23 at 1 26 02 PM](https://github.com/24hoursmedia-craftcms/views-work/assets/806080/0bb6614b-0202-4eda-b00e-e75c1fa336ef)

**Comment by 24hoursmedia-craftcms** [comment]
Hi,

You need to set up a cron job to reset the views every night at 00:00
It is documented at https://io.24hoursmedia.com/views-work/resetting-views

You can do it two ways, most service providers allow you to call a script according to a certain schedule,

or if that is not supported, in the settings you can get a special url that should be called every night.
you can call that url by a service such as easycron.com every night

(as documented).

I hope this helped you,

Mike

**Comment by zenbug** [comment]
Oh, I see. I read the docs, but didn't get that. For what it's worth, I'd suggest changing this:

`Some view counters need to be reset periodicaly`

to something like:

`If you want to use the Today view, you need to reset it every night.` 

...and include that on the pages that talk about it: 

https://io.24hoursmedia.com/views-work/show-the-pageviews
https://io.24hoursmedia.com/views-work/query-popular-content

Anyway, thank you for the help!

**Comment by 24hoursmedia-craftcms** [comment]
Thank you for the suggestion, I plan on making an update for views work somewhere in the next months,

I’ll consider updating the documentation and maybe also to handle resetting the views in craft itself at the first request of the day
If the user does not have or want access to cron jobs (it would not be as accurate though as through a cron job).

Regards, thank you for the feedback,

Mike

Op 24 jul. 2023, om 14:55 heeft zenbug ***@***.***> het volgende geschreven:


Oh, I see. I read the docs, but didn't get that. For what it's worth, I'd suggest changing this:

Some view counters need to be reset periodicaly

to something like:

If you want to use the Today view, you need to reset it every night.

...and include that on the pages that talk about it:

https://io.24hoursmedia.com/views-work/show-the-pageviews <https://io.24hoursmedia.com/views-work/show-the-pageviews> 
https://io.24hoursmedia.com/views-work/query-popular-content <https://io.24hoursmedia.com/views-work/query-popular-content> 

Anyway, thank you for the help!
