### ISSUE TITLE
1.1.12 broke /admin/dashboard

### ISSUE THREAD

**Issue by Wiejeben** [24hoursmedia-craftcms/views-work#2]
Failed to instantiate component or class "twentyfourhoursmedia\viewswork\assetbundles\viewswork\ViewsWorkAsset".

Seems to have something to do with:
```twig
{% do view.registerAssetBundle("twentyfourhoursmedia\\viewswork\\assetbundles\\viewswork\\ViewsWorkAsset") %}
```
`/vendor/twentyfourhoursmedia/views-work/src/templates/_components/widgets/ViewsWorkWidget_settings.twig` at line 18

I noticed that you removed the `ViewsWorkAsset` in 1.1.12, this is causing problems on my acceptance server, no problems locally for some reason. Downgrading to 1.1.11 for now.

PHP 7.4.11
Craft 3.5.14
ViewWorks 1.1.12

Thanks for looking into it in advance!

**Comment by 24hoursmedia-craftcms** [comment]
Thank you for reporting, it should have been fixed in v1.1.13

Sorry for the inconvenience, there were some upgrade problems to ensure composer v2 compatibility, complicated by case-insensitive file systems on docker/osx,win versus case sensitive on most production servers.
