### ISSUE TITLE
Same views numbers for all the periods

### ISSUE THREAD

**Issue by lucosius** [24hoursmedia-craftcms/views-work#59]
Hello,

I have the problem that all the periods have the same views number. All time, month, week and daily lists have exact same articles with exact same amount of views.

https://prnt.sc/14yksrh

I have placed {{ entry | views_work_image }} at the bottom of my articles template.

How can I solve this problem?

**Comment by 24hoursmedia-craftcms** [comment]
Hi @lucosius ,

The views need to be reset daily. You can do this with a cron job, or call a special url (automated by services such as easycron.com).

The process is described in:

https://io.24hoursmedia.com/views-work/setup
