### ISSUE TITLE
Views are not resetted

### ISSUE THREAD

**Issue by lucosius** [24hoursmedia-craftcms/views-work#93]
Hello,

Recently I updated to CraftCMS 4 and now I have an issue that cronjob is not working. I have this setup in my cpanel:

```
5 | 0 | * | * | * | php /home/telefonai/public_html/craft views-work/default/reset-views
-- | -- | -- | -- | -- | --
```

It used to work as a charm before the upgrade. Where should I look for the issue?

I'm running Craft CMS 4.2.5.1 and Views Work 2.0.1.0

**Comment by 24hoursmedia-craftcms** [comment]
Hi, I experience no problems with Views Work 2.0.1.0 and CMS 4.2.5.1

What does the output of the command say if you run it manually?
And does the url-based reset work?

**Comment by 24hoursmedia-craftcms** [comment]
Sorry lacking more info, can't duplicate
